myshop/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
]

myshop/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

myshop/orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$', views.OrderCreate, name='OrderCreate'),
    url(r'^admin/order/(?P<order_id>\d+)/$', views.AdminOrderDetail, name='AdminOrderDetail'),
    url(r'^admin/order/(?P<order_id>\d+)/pdf/$', views.AdminOrderPDF, name='AdminOrderPDF')

]

myshop/shop/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.ProductList, name='ProductList'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.ProductList, name='ProductListByCategory'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ProductDetail, name='ProductDetail'),
]

myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/cart/forms.py
# -*- coding: utf-8 -*-
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                                  update_quantity=cd['update'])
    return redirect('cart:CartDetail')

def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')

def CartDetail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                                        initial={
                                            'quantity': item['quantity'],
                                            'update': True
                                        })
    return render(request, 'cart/detail.html', {'cart': cart})

myshop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}

{% block title %}
  Ваша корзина товаров
{% endblock %}

{% block content %}
  <h1>Ваша корзина товаров</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Изображение</th>
        <th>Продукт</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Полная цена</th>
        <th>Цена</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{{ product.image.url }}" alt="" />
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td><form action="{% url "cart:CartAdd" product.id %}" method="post" class="add">
    		{{ item.update_quantity_form.quantity }}
   		{{ item.update_quantity_form.update }}
   		{% csrf_token %}
    		<input type="submit" value="Обновить">
	    </form></td>
            <td><a href="{% url "cart:CartRemove" product.id %}">Удалить</a></td>
            <td class="num">{{ item.price }} руб.</td>
            <td class="num">{{ item.total_price }} руб.</td>
          </tr>
        {% endwith %}
      {% endfor %}
        <tr class="total">
          <td>Total</td>
          <td colspan="4"></td>
          <td class="num">{{ cart.get_total_price }} руб.</td>
        </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url "shop:ProductList"%}" class="btn">Продолжить Шопинг</a>
    <a href="{% url "orders:OrderCreate" %}" class="btn">Оформить заказ</a>
  </p>
{% endblock %}